stages:
  - build

variables:
  # 设置Docker镜像 - 使用Windows Server Core基础镜像
  DOTNET_IMAGE: mcr.microsoft.com/dotnet/framework/sdk:4.6.2-windowsservercore-ltsc2016
  # 设置工作目录
  WORKING_DIR: "D:/Repo/project"
  # MSBuild路径
  MSBUILD_PATH: "C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/MSBuild/15.0/Bin/MSBuild.exe"

# 构建阶段
build:
  stage: build
  tags:
    - windows  # 确保使用Windows Runner
  image: $DOTNET_IMAGE
  script:
    - echo "Starting build process..."
    - echo "Current directory: $(pwd)"
    - echo "MSBuild version:"
    - $MSBUILD_PATH /version
    - echo "Restoring NuGet packages..."
    - nuget restore "$WORKING_DIR/pj.sln"
    - echo "Building solution..."
    - $MSBUILD_PATH "$WORKING_DIR/pj.sln" /t:Rebuild /p:Configuration=Release /p:Platform="Any CPU" /p:RestorePackages=false
    - if (!(Test-Path "$WORKING_DIR/bin/Release")) { throw "Build failed - Release directory not found" }
    - echo "Build completed successfully"
    
  artifacts:
    paths:
      - $WORKING_DIR/bin/Release/
    expire_in: 1 week
